language: android
jdk: oraclejdk7

android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-22.0.1
    - android-22

sudo: false

before_script:
    - chmod +x gradlew

script:
    - ./gradlew clean assembleRelease --stacktrace

branches:
  only:
    - master
    - develop