language: android
jdk: oraclejdk7

android:
  components:
    - android-23
    - platform-tools
    - tools
    - sys-img-armeabi-v7a-android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-23.0.2

sudo: false

before_script:
    - chmod +x gradlew

script:
    - ./gradlew clean assembleFullRelease --stacktrace --info

branches:
  only:
    - master
    - develop